on: [push]

jobs:
  convert-to-electron:
    runs-on: ubuntu-latest
    name: A job to convert to electron
    steps:
    - name: Convert step
      id: convert
      uses: unfoldingWord-box3/react-to-electron-action@v1.0.2
      with:
        appname: 'rrouter'
        appid: 'io.github.mandolyte'
        path: 'rrouter'
    # Use the output from the `hello` step
    - name: Get outputs (the inputs)
      run: |
        echo "The appname was ${{ steps.convert.outputs.appname }}"
        echo "The appid was ${{ steps.convert.outputs.appid }}"
        echo "The path was ${{ steps.convert.outputs.path }}"
        