# test workflow for react to electron action
on:
  push:
    tags:
      - 'v*' # any push with a tag in semver format

jobs:
  convert-to-electron:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: A job to convert to electron
    steps:
      - name: Show Env
        run: |
          echo Home is $HOME 
          echo Working Directory is $GITHUB_WORKSPACE
          echo OS is ${{ matrix.os }}
          echo Version is ${GITHUB_REF##*v}
        shell: bash

      - name: Checkout Code
        uses: actions/checkout@v2
      
      # setup node
      - name: Use node
        uses: actions/setup-node@v1
      
      # convert to electron
      - name: Convert step
        id: convert
        uses: unfoldingWord-box3/react-to-electron-action@v1.0.16
        with:
          appname: 'rrouter'
          appid: 'io.github.mandolyte'
          path: 'rrouter'
          version: '1.0.0'

      - name: Get outputs (the inputs)
        run: |
          echo "The appname was ${{ steps.convert.outputs.appname }}"
          echo "The appid was ${{ steps.convert.outputs.appid }}"
          echo "The path was ${{ steps.convert.outputs.path }}"
          echo "artifact name is ${{ steps.convert.outputs.artifactname }}"
          echo "   asset name is ${{ steps.convert.outputs.assetname }}"

      # show the platform installers
      - name: show platforms
        run: ls ./dist
        working-directory: ./electron
        shell: bash
      
      # upload the assets to the release
      - name: Upload Release Assets
        uses: svenstaro/upload-release-action@v1-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./electron/dist/${{ steps.convert.outputs.artifactname }}"
          asset_name: ${{ steps.convert.outputs.assetname }}
          tag: ${{ github.ref }}
          overwrite: true
